### ISSUE TITLE
Paying cost of spell

### ISSUE THREAD

**Issue by pardahlman** [pardahlman/mtg-boardgame.io#7]
Reading the rule book  it sounds like a spell is put in the stack and one that is done, its cost is payed.

> To cast a spell is to take it from where it is (usually the hand), put it on the stack, and pay its costs, so that it will eventually resolve and have its effect. Casting a spell includes proposal of the spell (rules 601.2a–d) and determination and payment of costs

So, I'm thinking on how we might implement this 🤓 

Perhaps it makes sense for each `player` to have a `manaPool` that can be filled by tapping lands or activating mana abilities. Perhaps needless to say, but any "color choices" (lands with more than one color, ...) are resolved when tapping the land, so that the pool contains the resolved mana. Once a spell is being cast, the game looks in the `manaPool` to see if it has sufficient resources to pay the cost of the spell. If it does, then it soles payment automatically. If not, the player is prompted to add more mana in the pool.

We could model spells such that it is responsible to mutate the game state according to its costs (removing mana from the pool, decrease player life, prompt player to sacrifice creature, ...) - this allows us to introduce new types of costs without changing logic in the game engine.

**Comment by Korla** [comment]
I think the game should have an API to add mana to the mana pool, and another API to cast a spell, which includes how the player should pay its cost. The game then checks if that way of paying for the spell is legitimate, and executes the spell if that is ok.

**Comment by Korla** [comment]
So one move is `AddMana`, and another is `PlaySpell`. We will pay for a lot of things which aren't spells. Activated and Triggered abilities, for example.
